name: 'build-test'
on:
    pull_request:
    push:
        branches:
            - main
            - develop
            - 'releases/*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: yarn install --frozen-lockfile
            - run: yarn run all
              env:
                  GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: 'Test run (REMOVE_TITLE_LINE: false)'
              uses: ./
              id: run1
              with:
                  GITHUB_AUTH: '${{ secrets.GITHUB_TOKEN }}'
                  LABEL_SETTINGS_FILE_PATH: './.github/lerna-changelog.json'
                  TAG_FROM: '4b825dc642cb6eb9a060e54bf8d69288fbee4904'
                  TAG_TO: 'origin/main'
                  REMOVE_TITLE_LINE: 'false'
            - run: echo "${{steps.run1.outputs.markdown}}"
            - name: 'Test run (REMOVE_TITLE_LINE: true)'
              uses: ./
              id: run2
              with:
                  GITHUB_AUTH: '${{ secrets.GITHUB_TOKEN }}'
                  LABEL_SETTINGS_FILE_PATH: './.github/lerna-changelog.json'
                  TAG_FROM: '4b825dc642cb6eb9a060e54bf8d69288fbee4904'
                  TAG_TO: 'origin/main'
                  REMOVE_TITLE_LINE: 'true'
            - run: echo "${{steps.run2.outputs.markdown}}"
